Repository apify/apify-client-js, pull requests merged in 2023-03, with the labels that each got.

#326 chore: update dev dependencies
  .github/workflows/check.yml
  .github/workflows/pr_toolkit.yml
  .github/workflows/release.yml
  jest.config.ts
  package-lock.json
  package.json
  test/_helper.js
  test/mock_server/server.js
  website/package-lock.json
  website/package.json
Labels: t-tooling

#331 fix(actor): fix types for actor run
  src/resource_clients/actor.ts
  src/resource_clients/run_collection.ts
Labels: t-platform

#332 fix: improve reading of the version when using bundlers
  src/http_client.ts
  src/utils.ts
Labels: t-tooling

#330 feat: add support for `maxItems` in run options
  src/resource_clients/actor.ts
  src/resource_clients/task.ts
  test/actors.test.js
  test/tasks.test.js
Labels: t-c&c

#335 feat(repo): repository links
  package.json
Labels: adhoc, t-platform

#333 feat: add "standard" handing for setStatusMessage
  package-lock.json
  package.json
  src/apify_client.ts
Labels: t-tooling

#347 chore: Unify YAML file extensions to .yaml
  .github/workflows/check.yaml
  .github/workflows/pr_toolkit.yaml
  .github/workflows/release.yaml
Labels: t-platform
