Repository apify/apify-client-js, pull requests merged in 2023-10, with the labels that each got.

#426 feat: add new webhook fields
  src/resource_clients/webhook.ts
  src/resource_clients/webhook_collection.ts
Labels: t-console

#428 feat: Add delete to runs and builds
  src/resource_clients/build.ts
  src/resource_clients/run.ts
Labels: t-c&c

#430 ci: test on node 20 + improve tests workflow
  .github/workflows/check.yaml
  .github/workflows/pr_toolkit.yaml
Labels: adhoc, debt, t-tooling

#440 feat: Add how to install javascript Apify client
  docs/index.md
  website/versioned_docs/version-2.8/index.md
Labels: t-web
