Repository apify/apify-client-js, pull requests merged in 2023-05, with the labels that each got.

#353 feat: Rename APIFY_ACTOR_MAX_ITEMS to ACTOR_MAX_PAID_DATASET_ITEMS
  src/resource_clients/actor.ts
Labels: t-c&c

#354 chore: Use new workflow secrets
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
Labels: adhoc, t-platform

#355 feat(runs, builds): add usage usd into actor run and build types
  src/resource_clients/actor.ts
  src/resource_clients/build.ts
  src/resource_clients/build_collection.ts
Labels: t-platform

#357 chore: invalidate CloudFront cache after docs deploy
  .github/workflows/docs.yaml
Labels: adhoc, t-platform
