Repository apify/apify-client-js, pull requests merged in 2024-01, with the labels that each got.

#486 fix: add missing properties to `ActorCollectionCreateOptions` type
  package.json
  src/resource_clients/actor_collection.ts
Labels: t-platform

#489 feat(request-queue): Limit payload size for batchAddRequests()
  src/resource_clients/request_queue.ts
  src/utils.ts
  test/request_queues.test.js
Labels: t-platform, tested

#493 chore(request-queue): use const from shared
  package-lock.json
  package.json
  src/resource_clients/request_queue.ts
Labels: adhoc, t-platform

#488 docs: add codeowner for documentation
  .github/CODEOWNERS
Labels: t-docs
