Repository apify/apify-client-js, pull requests merged in 2024-02, with the labels that each got.

#506 fix: publish browser bundle
  package.json
Labels: adhoc, t-tooling

#505 fix: update axios to v1.6
  package-lock.json
  package.json
  src/http_client.ts
  src/interceptors.ts
  src/resource_clients/key_value_store.ts
  test/http_client.test.js
  test/request_queues.test.js
Labels: t-tooling, tested

#510 feat: add `KeyValueStore.recordExists()` method
  src/resource_clients/key_value_store.ts
  src/utils.ts
  test/key_value_stores.test.js
Labels: t-tooling, tested

#509 feat: add log() method to BuildClient (JS)
  src/resource_clients/build.ts
  test/builds.test.js
  test/mock_server/routes/builds.js
Labels: t-platform, tested

#468 feat: add `runs()` and `builds()` top level endpoints
  src/apify_client.ts
  src/resource_clients/build_collection.ts
  src/resource_clients/run_collection.ts
  test/builds.test.js
  test/mock_server/routes/builds.js
  test/mock_server/routes/runs.js
  test/runs.test.js
Labels: t-platform

#515 fix: ensure axios headers are instance of AxiosHeaders via interceptor
  src/http_client.ts
  src/interceptors.ts
  test/http_client.test.js
Labels: adhoc, t-tooling, tested

#517 feat: add monthlyUsage() and limits() endpoints to UserClients
  src/resource_clients/user.ts
  test/mock_server/routes/users.js
  test/users.test.js
Labels: t-platform, tested

#519 feat: parse monthlyUsage.dailyServiceUsages[].date as Date
  src/resource_clients/user.ts
  src/utils.ts
  test/utils.test.js
Labels: t-platform, tested

#521 chore: remove warning when parseDateFields reaches depth limit
  src/utils.ts
Labels: adhoc, t-platform
