Repository apify/apify-client-js, pull requests merged in 2024-10, with the labels that each got.

#589 chore: Rename maxCostPerRun
  src/resource_clients/actor.ts
  src/resource_clients/task.ts
Labels: t-c&c

#593 chore: bump version and update dependencies
  .github/workflows/check.yaml
  package-lock.json
  package.json
  renovate.json
  src/http_client.ts
  test/actors.test.js
  test/builds.test.js
  test/datasets.test.js
  test/key_value_stores.test.js
  test/logs.test.js
  test/request_queues.test.js
  test/runs.test.js
  test/schedules.test.js
  test/store.test.ts
  test/tasks.test.js
  test/users.test.js
  test/webhook_dispatches.test.js
  test/webhooks.test.js
Labels: adhoc, t-tooling, tested

#592 feat: Rename maxCostPerRunUsd to maxTotalChargeUsd
  src/resource_clients/actor.ts
  src/resource_clients/task.ts
Labels: t-c&c

#595 feat: add user.updateLimits
  src/resource_clients/user.ts
  test/mock_server/routes/users.js
  test/users.test.js
Labels: t-console, tested

#602 feat: allow appending custom parts to the user agent
  package-lock.json
  package.json
  src/apify_client.ts
  src/http_client.ts
  src/utils.ts
  test/http_client.test.js
Labels: adhoc, t-tooling, tested
