Repository apify/apify-client-js, pull requests merged in 2025-04, with the labels that each got.

#670 chore: fix eslint config
  .github/scripts/before-beta-release.js
  eslint.config.mjs
  src/apify_api_error.ts
  src/base/resource_client.ts
  src/resource_clients/request_queue.ts
  src/timezones.ts
Labels: adhoc, t-tooling

#669 feat: add support for general resource access
  package-lock.json
  package.json
  src/resource_clients/actor.ts
  src/resource_clients/dataset.ts
  src/resource_clients/key_value_store.ts
  src/resource_clients/request_queue.ts
  src/resource_clients/run.ts
Labels: t-platform

#668 feat: add defaultBuild method
  src/resource_clients/actor.ts
  test/actors.test.js
  test/mock_server/routes/actors.js
Labels: adhoc, t-platform, tested

#672 chore: regenerate docs for version 2.12
  website/versioned_docs/version-2.12/api-packages.json
  website/versioned_docs/version-2.12/api-typedoc.json
Labels: adhoc, t-platform

#673 chore: update docs version 2.12
  website/versioned_docs/version-2.12/.gitignore
  website/versioned_docs/version-2.12/examples/index.md
  website/versioned_docs/version-2.12/index.md
  website/versioned_sidebars/version-2.12-sidebars.json
  website/versions.json
Labels: adhoc, t-platform

#677 fix: defaultBuild() returns BuildClient
  src/resource_clients/actor.ts
  test/actors.test.js
  test/mock_server/routes/actors.js
Labels: adhoc, t-platform, tested

#678 ci: Fix running code checks in release workflow
  .github/workflows/check.yaml
  .github/workflows/release.yaml
Labels: adhoc, t-tooling

#680 chore: fix openapi documentation link
  src/resource_clients/build.ts
Labels: adhoc, t-platform
