Repository apify/apify-client-js, pull requests merged in 2025-01, with the labels that each got.

#622 Update charge endpoint URL
  src/resource_clients/run.ts
Labels: t-c&c

#624 fix: change type `Build.actorDefinitions` to `Build.actorDefinition`
  src/resource_clients/build.ts
Labels: t-ai

#623 fix: Add ActorRunPricingInfo type
  src/resource_clients/actor.ts
Labels: adhoc, t-tooling, tested

#621 feat: add dataset.statistics
  src/resource_clients/dataset.ts
  test/datasets.test.js
  test/mock_server/routes/datasets.js
Labels: t-console, tested

#627 test: disable sandbox in puppeteer to get around CI issues
  test/_helper.js
Labels: adhoc, t-tooling, tested

#628 test: Add debug log, to see why test randomly failed
  test/_helper.js
Labels: adhoc, t-platform, tested

#626 feat: added getOpenApiSpecification() to BuildClient
  src/resource_clients/build.ts
  test/builds.test.js
  test/mock_server/routes/builds.js
Labels: adhoc, t-platform, tested

#631 refactor: rename /openapi -> /openapi.json
  src/resource_clients/build.ts
  test/builds.test.js
  test/mock_server/routes/builds.js
Labels: adhoc, t-platform, tested
