Repository apify/apify-client-js, pull requests merged in 2025-05, with the labels that each got.

#692 feat: allow overriding timeout of `KVS.setRecord` calls
  src/resource_clients/key_value_store.ts
  test/key_value_stores.test.js
  website/versioned_docs/version-2.12/api-packages.json
  website/versioned_docs/version-2.12/api-typedoc.json
Labels: adhoc, t-tooling, tested

#693 docs: improve docs for `waitForFinish` in `Actor.start`
  src/resource_clients/actor.ts
Labels: adhoc, t-tooling

#694 ci: Fix pre-release version handling
  .github/scripts/before-beta-release.js
  .github/workflows/pre_release.yaml
Labels: adhoc, t-tooling

#688 feat: list kv store keys by collection of prefix
  src/resource_clients/key_value_store.ts
  test/key_value_stores.test.js
Labels: t-console, tested

#700 feat: Add unlockRequests endpoint to RequestQueue client
  src/resource_clients/request_queue.ts
  test/mock_server/routes/request_queues.js
  test/request_queues.test.js
Labels: adhoc, t-platform, tested
